"""empty message

Revision ID: c08101943035
Revises: feb9c3f06888
Create Date: 2024-03-18 10:29:05.662108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08101943035'
down_revision = 'feb9c3f06888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('properties_fileName_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_unique_constraint('properties_fileName_key', ['fileName'])

    # ### end Alembic commands ###
