"""empty message

Revision ID: e6d9358f7f92
Revises: c08101943035
Create Date: 2024-03-18 10:48:43.329454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d9358f7f92'
down_revision = 'c08101943035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('numBedrms', sa.Integer(), nullable=True),
    sa.Column('numBathrms', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('propType', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('fileName', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
